# Generated by Django 5.2.8 on 2025-11-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0002_cliente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
