# Generated by Django 5.2.7 on 2025-11-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0004_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
