# Generated by Django 5.2.8 on 2025-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0005_servicio_activo_alter_producto_precio_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
