# Generated by Django 5.2.8 on 2025-11-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0006_atencion_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta Débito/Crédito'), ('transferencia', 'Transferencia Bancaria')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
