# Generated by Django 5.2.8 on 2025-11-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0007_atencion_metodo_pago_alter_producto_precio_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='codigo_transaccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='monto_pagado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atencion',
            name='vuelto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
