# Generated by Django 5.2.8 on 2025-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0008_atencion_codigo_transaccion_atencion_monto_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='codigo_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
